### ISSUE TITLE
Add support for Flux version 0.12?

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/MLJFlux.jl#107]
cc: @ablaom

**Comment by ablaom** [comment]
@ayush-1506 Are you able to have a look at this? 

@DilumAluthge BTW, compathelper action has been failing for MLJFlux and I don't understand the reason. If you  get a chance...

**Comment by DilumAluthge** [comment]
Can you delete the `COMPATHELPER_PRIV` secret and the corresponding deploy key? And then regenerate a new keypair? Add the private key as a secret named `COMPATHELPER_PRIV`, and make the public key a deploy key with write access.

**Comment by ablaom** [comment]
Done.

**Comment by DilumAluthge** [comment]
Hmm. Still looks broken. I'll take a look in a  little bit.

**Comment by ayush-1506** [comment]
Merged #110 which adds support for Flux 0.12. (All tests passed). Closing this issue.
