### ISSUE TITLE
Fix misleading CI badges

### ISSUE THREAD

**Issue by ablaom** [FluxML/MLJFlux.jl#140]
The badges now report fails, presumably because nightly has been failing, but for reasons unrelated to MLJFlux.jl. 

@DilumAluthge

**Comment by ablaom** [comment]
Maybe we need a separate GitHub action for nightly??

**Comment by ablaom** [comment]
I've split the nightly ci and don't understand while the badges on dev still read "fail".

**Comment by DilumAluthge** [comment]
I think this was fixed by https://github.com/FluxML/MLJFlux.jl/pull/149, at least for the dev branch.

@ablaom Take a look at the README and let me know if it looks correct for the dev branch.

Then you'll need to merge dev into master to fix the master badge.
