### ISSUE TITLE
Re-instante depwarnings in CI

### ISSUE THREAD

**Issue by ablaom** [FluxML/MLJFlux.jl#182]
These were temporarily disabled to address a fail unrelated to MLJFlux.jl.

Re-instate when this issue is resolved:

- [x] https://github.com/FluxML/Zygote.jl/issues/1030

**Comment by oxinabox** [comment]
I don't think this is needed.
I think depwarning in testing are occationally useful.
In CI, almost never.
Because CI tells you if you can merge *this* PR.
You don't want to encourage people to fix depwarning during some unrelated PR.

**Comment by ablaom** [comment]
Thanks. Makes sense. I was just using the generic ci.yml provided by others. Incidentally, my attempt to remove depwarns from ci failed anyway. How do you do this?

**Comment by oxinabox** [comment]
I don't know how for GHA.
I have only seen it done on Invenia's very custom GitLab CI system
