### ISSUE TITLE
Builder does not appear to build an architecture compatible with supplied data

### ISSUE THREAD

**Issue by Moelf** [FluxML/MLJFlux.jl#216]
### Package Version

MLJFlux v0.2.9

### Julia Version

1.8.2

### OS / Environment

Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 96 × AMD EPYC 7402 24-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 8 on 96 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_REVISE_POLL = 1

### Describe the bug

```julia
┌ Error: Builder does not appear to build an architecture compatible with supplied data. 
└ @ MLJFlux /home/jiling/.julia/packages/MLJFlux/6XVNm/src/mlj_model_interface.jl:61
┌ Error: Builder does not appear to build an architecture compatible with supplied data. 
└ @ MLJFlux /home/jiling/.julia/packages/MLJFlux/6XVNm/src/mlj_model_interface.jl:71
┌ Error: Problem fitting the machine machine(NeuralNetworkClassifier(builder = GenericBuilder(apply = #9), …), …). 
└ @ MLJBase /home/jiling/.julia/packages/MLJBase/6ooqv/src/machines.jl:627
┌ Info: Running type checks... 
└ @ MLJBase /home/jiling/.julia/packages/MLJBase/6ooqv/src/machines.jl:633
┌ Info: Type checks okay. 
└ @ MLJBase /home/jiling/.julia/packages/MLJBase/6ooqv/src/machines.jl:637

MethodError: objects of type Nothing are not callable
```

### Steps to Reproduce

```julia
builder = MLJFlux.@builder Chain(
    Dense(n_in, 30),
    Dense(30, n_out)
)

tree = NNClassifier(; builder, batch_size=512, acceleration=CUDALibs(), epochs=40)
```

meanwhile this works
```
builder = MLJFlux.MLP(;hidden=(10,10))
```

### Expected Results

work?

### Observed Results

error

**Comment by jbrea** [comment]
I cannot reproduce this error. Can you give more information about the input and output given to the machine (ideally a MWE)?

**Comment by ablaom** [comment]
I also cannot reproduce and agree more context would be helpful.
