### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/MLJFlux.jl#231]
Hi!

Can I please get a new release here? I am trying to use the latest Flux 0.14 with MLJFlux but the last released MLJFlux is only compatible with Flux 0.13.

**Comment by DilumAluthge** [comment]
@ablaom

**Comment by ablaom** [comment]
The holdup is here: https://github.com/FluxML/MLJFlux.jl/pull/232

Be good if someone can help out.

**Comment by ablaom** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/90252.

Thank you for your patience.

**Comment by mohamed82008** [comment]
Thank you!
