### ISSUE TITLE
Error `fit` GPU

### ISSUE THREAD

**Issue by andrewrosemberg** [FluxML/MLJFlux.jl#247]
*Sorry if this is not the place for this issue! I am not quite sure where to raise it*

I am hitting the same error as the one in the [CI build](https://buildkite.com/julialang/mljflux-dot-jl/builds/368#018b87ea-466e-4b5b-9981-5202a974ad54/327-638).

I understand this is an upstream issue. Do you know if this issue has been raised elsewhere?

**Comment by ablaom** [comment]
Thanks for flagging and looking into this!

I also notice the error (which has surfaced without any change to to the MLJFlux source code) but was still scratching my head about it.

> I understand this is an upstream issue. Do you know if this issue has been raised elsewhere?

If you have isolated the issue, be great to note your progress here. No, I have not raised anything elsewhere.

**Comment by andrewrosemberg** [comment]
Understood. Yeah this is a weird bug. I am going through the functions of the Stacktrace to see which ones were modified upstream. If it is still not clear what the problem is, I will fix the packages upstream to older tags.

I will post here what I find.

**Comment by andrewrosemberg** [comment]
I believe the error is in Zygote.jl.

Other people have hit the error since a change there: https://github.com/FluxML/Zygote.jl/issues/1470

**Comment by andrewrosemberg** [comment]
Correct me if I am wrong, but I believe this is now fixed :)

**Comment by andrewrosemberg** [comment]
Correct me if I am wrong, but I believe this is now fixed :) I will close the issue but feel free to re-open if I got it wrong.
