### ISSUE TITLE
CompatHelper failing

### ISSUE THREAD

**Issue by ablaom** [FluxML/MLJFlux.jl#55]
According to the [log](https://github.com/alan-turing-institute/MLJFlux.jl/runs/885938257?check_suite_focus=true):

![Screen Shot 2020-07-20 at 7 27 23 AM](https://user-images.githubusercontent.com/30517088/87883292-7b234d80-ca5a-11ea-83b1-07ccde82a577.png)

But I can't find where it's getting this path from. There's nothing about any dev branch in .github/workflows that I can find (https://github.com/alan-turing-institute/MLJFlux.jl/blob/master/.github/workflows/CompatHelper.yml) ??!!

**Comment by DilumAluthge** [comment]
You probably have a bad manifest somewhere in your repo.

One option is to delete the offending manifest.

The other option is to tell CompatHelper to ignore manifests. This can be implemented by looking here: https://github.com/JuliaRegistries/CompatHelper.jl#example-1-disable-all-precommit-hooks (see the section on disabling all precommit hooks)

**Comment by ablaom** [comment]
@DilumAluthge Ahaaa! The problem is examples/Manifest.tom/ .

Thanks - that would have taken  me ages to find.
