### ISSUE TITLE
TODO: Set up the GPU continuous integration (CI) for MLJFlux.jl

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/MLJFlux.jl#65]
cc: @ablaom 
cc: @maleadt

**Comment by DilumAluthge** [comment]
So.... this is going to be really tricky.

We now use Buildkite for JuliaGPU CI. In order to set up Buildkite, there is one step that can only be completed by a user that is both a Julia Buildkite admin AND an owner of the organization that owns the repo in question.

Is there any chance that the Alan Turing Institute would be willing to temporarily make me or @maleadt an owner of the alan-turing-institute GitHub organization so that we can set up Buildkite on this organization?

If not, perhaps we could move this repo to the FluxML organization instead?

I do think that it will be important to have GPU CI on this repo, since many users will want to use GPUs for neural networks.

**Comment by ablaom** [comment]
> Is there any chance that the Alan Turing Institute would be willing to temporarily make me or @maleadt an owner of the alan-turing-institute GitHub organization so that we can set up Buildkite on this organization?

Given the fact that I still don't have authority to create new repos, I expect this is a tall order. I think moving to FluxML would probably be easier  and a better long term arrangement (and I think @ayush-1506 is probably already a member). I'll make enquiries.
