### ISSUE TITLE
Add a GPU example to the README?

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/MLJFlux.jl#78]
It would be nice to have a GPU example in the README.

Maybe we could have two versions of the MNIST example? A CPU version and a GPU version? That way we could show people the differences between using MLJFlux on CPU versus GPU?

**Comment by ablaom** [comment]
If someone wants to pick this up, the suggested comparison is essentially in the test suite. Might be worth substituting a fancier architecture (`Builder` object).

**Comment by ayush-1506** [comment]
I can take this up, found some time on my hands. Kindly let me know.
(Also, I haven't been very active on slack so might not be completely up to date with recent developments)

@ablaom

**Comment by ablaom** [comment]
@ayush-1506 Thanks! FYI I am addressing this issue and bits of #56 in a PR I'm posting very soon.

**Comment by ablaom** [comment]
Adding further examples, or more in-depth ones will certainly be very useful, however
