### ISSUE TITLE
Switch code coverage to use Codecov?

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/MLJFlux.jl#82]
Right now, MLJFlux.jl uses Coveralls.io for code coverage.

However, if I understand correctly, the JuliaGPU Buildkite plugin only supports Codecov.

Any objection to switching code coverage over to Codecov?

**Comment by ablaom** [comment]
No objection

**Comment by DilumAluthge** [comment]
Cool. I'll try to work on this today.

**Comment by ablaom** [comment]
@DilumAluthge Can we close this now?
