### ISSUE TITLE
Replace `train!` with a custom loop

### ISSUE THREAD

**Issue by ablaom** [FluxML/MLJFlux.jl#89]
The current requirement to zip inputs `X` and targets `y` in the `data` object required by `MLJFlux.train!` is a deal breaker as far as implementing the [new data front-end](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Implementing-a-data-front-end-1) provided by MLJ. Moreover, a discussion on slack has revealed no clear performance reason for zipping the `X` and `y`.

So, with implementing a new data front-end in mind, I propose we refactor `MLJFlux.fit!` as follows:

- Write and test a customised version of `Flux.train!(loss_func, Flux.params(chain), data, optimiser)` with new signature `train!(loss_func, Flux.params(chain), optimiser, X, y)`. Here `X` is a vector of arrays - one array for each **input** observation - where the last dimension of the array corresponds to batches. The same for `y`, but this is for **target** observations. Basically, this is the unzipped version of the status quo.

-  Change the signature of MLJFlux.fit! accordingly, from 

```
fit!(chain, optimiser, loss, epochs, lambda, alpha, verbosity, data, acceleration)
```
to
```
fit!(chain, optimiser, loss, epochs, lambda, alpha, verbosity, acceleration, X, y)
``` 

- Refactor the `collate` method to spit out `X, y` in the form above, rather than the zipped version (easy). This function essentially becomes the `refactor` methods for the new data font-end - but let's leave that discussion for another issue.

@ayush-1506 You interested in this?

**Comment by ayush-1506** [comment]
Sure, will pick this up.
