### ISSUE TITLE
Suppress gpu testing in PR to dev branch?

### ISSUE THREAD

**Issue by ablaom** [FluxML/MLJFlux.jl#92]
Testing on the GPU seems very slow (at least 30min, sometimes). 

Thoughts anyone?

**Comment by DilumAluthge** [comment]
Seems fine to me. 

We'd still run the GPU CI on the PRs that merge `dev` into `master`, right?

**Comment by DilumAluthge** [comment]
This is done. Implemented in #93 

We WILL run GPU CI on the following:
1. PRs to master
2. Pushes to master
3. Pushes to dev

We will NOT run GPU CI on the following:
1. PRs to dev
